language: node_js
node_js:
  - stable
script:
  - npm run lint && npm run build && npm run csslint && npm run test && npm run downloadsolc
  - ./ci/browser_tests.sh
deploy:
  provider: script
  script: ci/deploy_from_travis.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    - ENCRYPTION_LABEL="b5c2730599da"
    - COMMIT_AUTHOR_EMAIL="chris@ethereum.org"
    - COMMIT_AUTHOR="Travis CI"
    - PUSH_REPO="git@github.com:ethereum/browser-solidity.git"
    - FILES_TO_PACKAGE="assets background.js build icon.png index.html manifest.json README.md soljson.js"
cache: false
