language: node_js
node_js:
  - stable
script:
  - npm run lint && npm run csslint && npm run test && npm run downloadsolc && npm run make-mock-compiler && npm run build
  - ./ci/browser_tests.sh
deploy:
  provider: script
  script: ci/deploy_from_travis.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    - ENCRYPTION_LABEL1="b5c2730599da"
    - ENCRYPTION_LABEL2="85f76a180658"
    - COMMIT_AUTHOR_EMAIL="chris@ethereum.org"
    - COMMIT_AUTHOR="Travis CI"
    - FILES_TO_PACKAGE="assets background.js build icon.png index.html manifest.json README.md soljson.js"
cache: false
