language: node_js
node_js:
  - "10"
branches:
  only:
  - master
  - remix_live
script:
  - npm run lint && npm run test && npm run make-mock-compiler && npm run build
  - ./ci/browser_tests.sh
deploy:
  - provider: script
    script: ci/deploy_from_travis_master.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ci/deploy_from_travis_remix-live.sh
    skip_cleanup: true
    on:
      branch: remix_live
env:
  global:
    - ENCRYPTION_LABEL2="85f76a180658"
    - ENCRYPTION_LABEL3="3737d4fd78e9"
    - COMMIT_AUTHOR_EMAIL="chris@ethereum.org"
    - COMMIT_AUTHOR="Travis CI"
    - FILES_TO_PACKAGE="assets background.js build icon.png index.html manifest.json README.md soljson.js"
cache: false
