language: node_js
node_js:
  - stable
before_script:
  - npm run serve &
script:
  - npm run lint && npm run test && npm run build && npm run browser-test-sc
  - pkill node
addons:
 sauce_connect:
   username: "chriseth"
   access_key: "b781828a-9e9c-43d8-89d4-2fbb879595ca"
deploy:
  provider: script
  script: ci/deploy_from_travis.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - ENCRYPTION_LABEL="b5c2730599da"
  - COMMIT_AUTHOR_EMAIL="chris@ethereum.org"
  - COMMIT_AUTHOR="Travis CI"
  - PUSH_REPO="git@github.com:ethereum/browser-solidity.git"
  - FILES_TO_PACKAGE="assets background.js build icon.png index.html manifest.json README.md"
