# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  remix-ide:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    environment:
      - ENCRYPTION_LABEL1: "b5c2730599da"
      - ENCRYPTION_LABEL2: "85f76a180658"
      - ENCRYPTION_LABEL3: "1b1c118ea62d"
      - COMMIT_AUTHOR_EMAIL: "chris@ethereum.org"
      - COMMIT_AUTHOR: "Circle CI"
      - FILES_TO_PACKAGE: "assets background.js build icon.png index.html manifest.json README.md soljson.js"
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dep-bundle-18-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dep-bundle-18-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules
      - run: npm run lint && npm run test && npm run downloadsolc && npm run make-mock-compiler && npm run build
      - run: ./ci/browser_tests.sh
  
  remix-debugger:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11.2
    
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dep-bundle-13-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dep-bundle-13-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules
      - run: npm run build_debugger
      - run: ./ci/browser_tests_debugger.sh

workflows:
  version: 2
  build_all:
    jobs:
      - remix-ide
      - remix-debugger
